EMX Digital: Adding tests for validating TCF v1.1 and TCF v2 consent string
prebid/prebid-server pull request #1457
Opened 2020-08-25 13:07 UTC by EMXDigital

Adding better testing coverage for GDPR TCF compliance

2020-08-25 22:08 UTC, guscarreon commented on adapters/emx_digital/usersync_test.go
>  	assert.NoError(t, err)
Can we rename test to `TestEMXDigitalSyncerTCF1` to be consistent with the test below?

2020-08-25 22:38 UTC, EMXDigital commented
Pushed up new func name

2020-08-26 21:06 UTC, SyntaxNode commented
Thank you for taking GDPR seriously and keeping quality top of mind.

The user sync tests are only very loosely related to TCF1 and TCF2. This test is designed to ensure the user sync url can be properly resolved with the template engine. The value of the privacy related strings are inconsequential here. You could replace the GDPR consent string with the simple string `"A"` and the test would be just as valid, and perhaps that would be a good idea.

The `gdpr.ValidateConsent` method is a thin wrapper on top of go-gdpr and already has extensive test coverage. There is no need to validate consent strings as part of this test. If you'd like to enhance the TCF parsing tests, you're welcome to also contribute to https://github.com/prebid/go-gdpr.

2020-09-09 03:59 UTC, SyntaxNode commented
@EMXDigital Checking in to see if you wanted to discuss my feedback, intend to update this test to use obviously fake values, or close this PR. Thank you.

2020-09-10 15:14 UTC, SyntaxNode requested changes
There is no need to call `gdpr.ValidateConsent` as that's only testing the hardcoded value. There's no need to separate TCF1 from TCF2 here, since it's just testing string replacement.

2020-09-24 14:09 UTC, SyntaxNode commented
Closing due to inactivity from author. If you get back to this in the future, please feel free to submit a new PR or reopen this one.

2020-09-24 14:09 UTC, closed without merging