Implement returnCreative
prebid/prebid-server pull request #1493
Opened 2020-09-11 20:26 UTC by guscarreon

This PR implements the ability to return empty ad markup strings in bidResponses when `ext.prebid.cache.vast.returnCreative` or `ext.prebid.cache.bids.returnCreative` is set to false in the incoming bid request. Please let me know your thoughts.

In summary:
**Bid request**
Note the new `returnCreative` field in the bid request extension: 
```
  {
    "id":"an-id",
    "imp":[
      {...}
    ],
    "site":{...},
    "user": {...},
    "ext": {
      "prebid":{
        "cache":{
          "bids":{
            "returnCreative":false //<-- new
          }
        }
      }
    }
  },
```

**Bid Response**
Given the `returnCreative` field in the bid request extension value set to false, an empty `AdM` value is returned in the bid response:
```
{
  "status" : 200,
  "body": {
    "id":"an-id",
    "seatBid":[
      {
        "bid": [
          {
            "id": "video1AdmVideo",
            "impid": "video1",
            "price": 20,
            "adm": "",  //<-- empty when returnCreative is false
            "adid": "1088",
            "w": 300,
            "h": 250,
            "ext": {
              "prebid": {
                "type": "video"
              }
            }
          }
        ],
        "seat": "a-biddername"
      }
    ]
  }
}
```

2020-09-15 18:55 UTC, hhhjort submitted a review, later dismissed
This is looking good. I am glad the code can tell the difference between a false `returnCreative` and a missing one.

2020-09-16 23:04 UTC, bsardo requested changes

2020-09-16 23:04 UTC, bsardo commented on exchange/exchange_test.go
> +					json.RawMessage(`{"prebid":{"cache":{"bids":{"returnCreative":false},"vastXml":{"returnCreative":true}}}}`),
Typo here as this json message doesn't match the description and is the same as the next test case.
This should probably be `{"bids":{"returnCreative":true},"vastXml":{"returnCreative":false}}`

2020-09-17 15:32 UTC, bsardo approved these changes

2020-09-17 15:40 UTC, hhhjort approved these changes

2020-09-17 15:41 UTC, merged