Add Adot adapter
prebid/prebid-server pull request #1605
Opened 2020-12-02 18:55 UTC by Giudici-a

Hi,

Following the #1599, i moved the converted version of the adapter here to make it cleaner.

2020-12-07 22:20 UTC, SyntaxNode commented on adapters/adot/adot_test.go
> +var jsonBidReq = getJsonByteForTesting("./static/adapter/adot/parallax_request_test.json")
This path is already scoped to this adapter package. Why the need for so many directory levels? It's also likely not necessary as you should be able to use our standard json test framework, no?

2020-12-07 22:20 UTC, SyntaxNode commented on adapters/adot/adot_test.go
> +	err1 := json.Unmarshal(getJsonByteForTesting("./static/adapter/adot/parallax_request_test.json"), &reqBanner)
Can you use our existing json test framework here?

2020-12-07 22:20 UTC, SyntaxNode commented on adapters/adot/adottest/supplemental/parallax.json
> +  "expectedBids": [
This is an incorrect name and is ignored by our test framework. Should be `expectedBidResponses`. See: https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html#adapter-code-tests

2020-12-07 22:20 UTC, SyntaxNode commented on adapters/adot/adot.go
> +		return nil, nil
Please add test coverage these error code conditions.

2020-12-09 16:12 UTC, Giudici-a commented
Thanks you for your responses, i made the changes about the returns that you asked.

2020-12-10 03:21 UTC, bsardo requested changes

2020-12-10 03:21 UTC, bsardo commented on adapters/adot/adot.go
> +			return openrtb_ext.BidTypeNative, nil
Could you add a native JSON test please?

2020-12-10 03:21 UTC, bsardo commented on adapters/adot/adot.go
> +		return nil, []error{err}
We're missing coverage here. See `adapters/connectad/connectadtest/supplemental/badresponse.json` as an example.

2020-12-10 03:21 UTC, bsardo commented on adapters/adot/adot_test.go
> +func TestBidResponseNoContent(t *testing.T) {
You could also achieve this coverage using the JSON test framework.

2020-12-14 16:56 UTC, Giudici-a commented
Hi, thanks again for your responses.
I pushed in the previous commit all the corrective request that you told me.

2020-12-16 09:27 UTC, SyntaxNode reviewed
Thank you for taking our feedback into account and updating the PR. Looks good to me, just except test coverage of the 400 error code from your bidding server.

2020-12-16 09:27 UTC, SyntaxNode commented on adapters/adot/adot.go
> +		return nil, []error{&errortypes.BadInput{
This specific error condition still looks to be untested.

2020-12-16 09:48 UTC, Giudici-a commented
I did the last think to test the status code 400, hope everything is good now.
I pushed it again in the previous commit, cause i think it's cleaner like that.
Thanks for all your feedback.

2020-12-17 03:30 UTC, bsardo requested changes
This is looking good, just two more comments. If you could make these changes and push them up in a new commit that'd be great. It would help me review the delta faster.

2020-12-17 03:30 UTC, bsardo commented on adapters/adot/adottest/supplemental/simple-audio.json
> +          "body": {
It looks like you've got `status` and `body` twice. Can you fix so there's only one occurrence of each?

2020-12-17 03:30 UTC, bsardo commented on adapters/adot/adot.go
> +		return nil, []error{err}
We're still missing coverage here for this error condition.

2020-12-17 22:14 UTC, SyntaxNode approved these changes

2020-12-17 22:18 UTC, SyntaxNode commented
Looks great. Thank you for addressing our feedback. Can you please post a link to your [documentation PR](https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html#user-documentation)? Then we should be all set.

2020-12-22 15:58 UTC, bsardo approved these changes
This looks good. @Giudici-a we're just waiting for you to open a doc PR before merging.

2021-01-05 18:20 UTC, SyntaxNode commented
@Giudici-a we approved this adapter, but you need to open a PR on the https://github.com/prebid/prebid.github.io project to change https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/adot.md per the [docs](https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html#user-documentation).

Specifically, you need to add `pbs: true` and a new table showing that placementId and parallax are the parameters for the PBS adapter - since the PBJS adapter has a different set of parameters. We appreciate the consistency with placementId though.

2021-01-09 00:13 UTC, bretg commented
docs PR https://github.com/prebid/prebid.github.io/pull/2609

2021-01-11 15:25 UTC, merged