Added Foreshop adapter.
prebid/prebid-server pull request #1653
Opened 2021-01-13 13:32 UTC by iN-Sight

(test endpoints)

2021-01-14 02:01 UTC, guscarreon requested changes

2021-01-14 02:05 UTC, guscarreon requested changes
Github actions validation is failing because of low unit-test coverage: 
```
 ok  	github.com/prebid/prebid-server/adapters/foreshop	0.024s	coverage: 3.6% of statements
Package has less than 30% code coverage. Run ./scripts/coverage.sh --html to see a detailed coverage report, and add tests to improve your coverage
```
Further coverage analysis:
```
╭─ ~/go/src/github.com/prebid/prebid-server/adapters/foreshop  ‹PR1653*›
╰─➤  go test -coverprofile=c.out
PASS
coverage: 3.6% of statements
ok      github.com/prebid/prebid-server/adapters/foreshop       0.744s

╭─ ~/go/src/github.com/prebid/prebid-server/adapters/foreshop  ‹PR1653*›
╰─➤  go tool cover -func=c.out
github.com/prebid/prebid-server/adapters/foreshop/foreshop.go:24:       Builder                 100.0%
github.com/prebid/prebid-server/adapters/foreshop/foreshop.go:32:       MakeRequests            0.0%
github.com/prebid/prebid-server/adapters/foreshop/foreshop.go:86:       MakeBids                0.0%
github.com/prebid/prebid-server/adapters/foreshop/foreshop.go:124:      getMediaType            0.0%
github.com/prebid/prebid-server/adapters/foreshop/foreshop.go:146:      getBidderData           0.0%
github.com/prebid/prebid-server/adapters/foreshop/usersync.go:11:       NewForeshopSyncer       0.0%
total:                                                                  (statements)            3.6%

2021-01-14 05:18 UTC, SyntaxNode commented on config/config.go
> +	v.SetDefault("adapters.foreshop.endpoint", "http://{{.Host}}/www/admin/api/bid-request-process.php")
It's actually a bit more than an encouragement. We will not allow adapters to pass through the host. PBS is not an open proxy.

We can guide you to a better solution. Are you using the host for debugging, vanity urls, or geo balancing?

2021-01-14 05:20 UTC, SyntaxNode commented on adapters/foreshop/foreshop.go
> +type Adapter struct {
Actually, we recommend the name "adapter" starting with a lower case letter to keep avoid exporting it.

2021-01-14 05:21 UTC, SyntaxNode commented
We recently updated our new adapter doc: https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html

That will guide you through our rules and best practices.

2021-01-14 12:16 UTC, iN-Sight commented
I appreciate the feedback and suggested corrections. Thanks!

2021-01-14 12:24 UTC, iN-Sight commented on adapters/foreshop/foreshop.go
> +type Adapter struct {
Noted. We currently don't actually have an endpoint for that, but I'll discuss this with the team and get that sorted.

2021-01-14 12:29 UTC, iN-Sight commented on config/config.go
> +	v.SetDefault("adapters.foreshop.endpoint", "http://{{.Host}}/www/admin/api/bid-request-process.php")
Noted. We don't currently have an endpoint for this, but I'll discuss this with the team and fix the URL.

2021-02-02 18:10 UTC, SyntaxNode commented
@iN-Sight Just wanted to check in how you're progressing. Is there anything we can assist with?

2021-02-03 01:28 UTC, iN-Sight commented
@SyntaxNode Hello, I appreciate you checking in!
After reviewing our current structure, I've decided that we aren't ready to submit a merge request yet for the adapter. We'll submit another request at another date.

Your guidance was nonetheless very valuable though. Thanks :)

Regarding the request, I'm closing this for now. My apologies if I was supposed to do this sooner.

2021-02-03 01:28 UTC, closed without merging

2021-02-03 01:40 UTC, SyntaxNode commented
No worries. You're welcome to open a PR again when you're ready.