Kargo: Normalize placementId naming
prebid/prebid-server pull request #2785
Opened 2023-05-17 14:19 UTC by jsadwith

In reference to https://github.com/prebid/prebid-server/issues/2654

Updated Prebid Server naming to use `placementId` to match that on Prebid.js: https://docs.prebid.org/dev-docs/bidders/kargo.html

The server-side code is backwards compatible to support both namings.

CC @SSuranie

2023-05-22 06:58 UTC, gargcreation1992 commented on adapters/kargo/params_test.go
> +	`{"placementID": "32321"}`,
Just curious, What should be the behaviour if both placementId and adSlotID are defined?

2023-05-22 06:58 UTC, gargcreation1992 reviewed
left one comment!

2023-05-22 07:01 UTC, gargcreation1992 requested changes
left one comment!

2023-05-22 14:18 UTC, jsadwith commented
@gargcreation1992 thanks Ashish. Just added an invalid test parameter for when both are set.

2023-05-23 11:28 UTC, gargcreation1992 commented on adapters/kargo/params_test.go
> +	`{"placementId": "11523", "adSlotID": "12345"}`, // Can't include both
👍

2023-05-23 11:28 UTC, gargcreation1992 approved these changes

2023-05-23 12:57 UTC, Sonali-More-Xandr approved these changes

2023-05-23 12:57 UTC, merged