New Adapter: Rise
prebid/prebid-server pull request #2815
Opened 2023-06-01 11:09 UTC by misha93m

2023-06-02 10:18 UTC, gargcreation1992 commented
@misha93m PR checks are failing. Requesting you to please check.

2023-06-05 05:50 UTC, onkarvhanumante commented
@misha93m  PR is created as Draft. Let us know when PR is ready for review

2023-06-06 09:32 UTC, giditietz commented on adapters/rise/rise.go
> +func Builder(_ openrtb_ext.BidderName, config config.Adapter, _ config.Server) (adapters.Bidder, error) {
why biddername is _?

2023-06-06 09:32 UTC, giditietz commented on adapters/rise/rise.go
> +	_ *adapters.ExtraRequestInfo) (
why ExtraRequestInfo is _?

2023-06-06 09:52 UTC, giditietz approved these changes

2023-06-07 06:14 UTC, gargcreation1992 commented
@misha93m Please let us know if this PR is ready to be reviewed.

2023-06-08 10:02 UTC, gargcreation1992 commented on adapters/rise/rise.go
> +) {
Nitpick - for consistency in the codebase please use single line for MakeRequests function declaration. 
```
func (a *adapter) MakeRequests(openRTBRequest *openrtb2.BidRequest, _ *adapters.ExtraRequestInfo) (requestsToBidder []*adapters.RequestData, errs []error) {
//your code
}
```

2023-06-08 10:08 UTC, gargcreation1992 commented on adapters/rise/rise.go
> +		if err := json.Unmarshal(imp.Ext, &bidderExt); err == nil {
you should not ignore Unmarshal error here. Please do the error handling properly.
```
if err := json.Unmarshal(imp.Ext, &bidderExt); err != nil {
     return "", err
}
```

2023-06-08 10:08 UTC, gargcreation1992 commented on adapters/rise/rise.go
> +			if err = json.Unmarshal(bidderExt.Bidder, &impExt); err == nil && impExt.PublisherID != "" {
same comment as above. Please do not ignore Unmarshaling error here.

2023-06-08 10:13 UTC, gargcreation1992 commented on adapters/rise/rise.go
> +	responseData *adapters.ResponseData) (*adapters.BidderResponse, []error) {
Requesting you to please move this to single line for consistency across the codebase.

2023-06-08 10:14 UTC, gargcreation1992 commented on adapters/rise/rise.go
> +	}
Checking response status code this way is correct but you could also make use of the following code - 
```
if httputil.IsResponseStatusCodeNoContent(response) {
		return nil, nil
	}

	if err := httputil.CheckResponseStatusCodeForErrors(response); err != nil {
		return nil, []error{err}
	}
```

2023-06-08 10:19 UTC, gargcreation1992 commented on adapters/rise/rise.go
> +			}
Warning - This is an anti-pattern. This code assumes that for multi-format bid request, mediatype will be set to type banner by default. I would recommend to set the mediaType based on bidder response. Your bidder should be able to set openrtb2.Bid.Mtype field and use that field here to get mediaTypeForImp. Even if your bidder does not support multi-format request, I would highly encourage you to make this change. [Here is an example.](https://github.com/prebid/prebid-server/blob/6b616196605030f568dae4a727d1a658de929417/adapters/ix/ix.go#L246-L247)

2023-06-08 10:22 UTC, gargcreation1992 commented on static/bidder-info/rise.yaml
> +  email: rise-prog-dev@risecodes.com
Sent an email confirmation to verify email addresss. Please reply received.

2023-06-08 10:24 UTC, gargcreation1992 commented on static/bidder-info/rise.yaml
> +  email: rise-prog-dev@risecodes.com
email verified. thanks!

2023-06-08 10:24 UTC, gargcreation1992 commented on static/bidder-info/rise.yaml
> +    url: https://pbs-cs.yellowblue.io/pbs-iframe?gdpr={{.GDPR}}&gdpr_consent={{.GDPRConsent}}&us_privacy={{.USPrivacy}}&redirect={{.RedirectURL}}
User sync URL works. 👍

2023-06-08 10:24 UTC, gargcreation1992 requested changes
Requesting few changes.

2023-06-08 12:14 UTC, onkarvhanumante commented on adapters/rise/rise.go
> +func (a *adapter) extractPublisherID(openRTBRequest *openrtb2.BidRequest) (string, error) {
`a *adapter` is not being referred inside function body.  Therefore no need to define `extractPublisherID` on `(a *adapter)`

2023-06-09 06:21 UTC, onkarvhanumante commented
@misha93m  tests are failing with following error:
```
Error: adapters/rise/rise.go:55:14: undefined: httputil.IsResponseStatusCodeNoContent
Error: adapters/rise/rise.go:59:21: undefined: httputil.CheckResponseStatusCodeForErrors
```
`IsResponseStatusCodeNoContent` and `CheckResponseStatusCodeForErrors` were moved to `adapters` package. Could you sync PR branch with master branch updates

2023-06-09 06:30 UTC, gargcreation1992 commented on adapters/rise/rise.go
> +	default:
In rise.yaml, you have defined that your bidder will be supporting just Banner and Video. I believe you might wanna error out if bidder response returns Audio or Native as bid type. So here is the code - 
```
switch bid.MType {
	case openrtb2.MarkupBanner:
		return openrtb_ext.BidTypeBanner, nil
	case openrtb2.MarkupVideo:
		return openrtb_ext.BidTypeVideo, nil
	default:
                 return "", fmt.Errorf("unsupported MType %d", bid.MType)
```

2023-06-09 09:13 UTC, onkarvhanumante approved these changes

2023-06-09 11:07 UTC, gargcreation1992 approved these changes

2023-06-09 11:08 UTC, gargcreation1992 approved these changes

2023-06-09 11:08 UTC, merged