updated to use iframe based usersync
prebid/prebid-server pull request #3660
Opened 2024-05-03 19:49 UTC by JoshuaMGoldstein

CPMStar: Use iframe based usersync

2024-05-06 15:28 UTC, bretg requested changes
can I convince you to leave the redirect approach in place and just add the iframe?

It better to have both approaches available for 2 reasons:

1. iframe syncs don't work for AMP
2. some publishers control iframe-vs-redirect sync

If you don't supply both options, you'll get left out in some scenarios.

If the publisher doesn't specify preferences, PBS will return the iframe sync.

2024-05-06 16:28 UTC, JoshuaMGoldstein commented
Thanks Bret, I updated to have both sync types.

2024-05-06 17:44 UTC, bretg approved these changes
LGTM

2024-05-13 13:02 UTC, gargcreation1992 approved these changes

2024-05-22 10:17 UTC, merged