CPMStar: add gvlVendorID
prebid/prebid-server pull request #3779
Opened 2024-06-28 07:55 UTC by JoshuaMGoldstein

CPMStar Bidder Adapter - Added GVL / TCF Vendor ID to bidder-info

2024-07-01 07:01 UTC, onkarvhanumante commented on static/bidder-info/cpmstar.yaml
> +gvlVendorID: 1317
@JoshuaMGoldstein  gvl id `1317` belongs to `Aditude, Inc`. 

```
curl https://vendor-list.consensu.org/v3/vendor-list.json | jq '.vendors."1317"'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  614k  100  614k    0     0  4965k      0 --:--:-- --:--:-- --:--:-- 4997k
{
  "id": 1317,
  "name": "Aditude, Inc.",
  "purposes": [
    1,
    3,
    4
  ],
  "legIntPurposes": [
    2,
    7,
    8,
    9,
    10
  ],
  "flexiblePurposes": [
    2,
    7,
    8,
    9,
    10
  ],
  "specialPurposes": [
    1,
    2
  ],
  "features": [
    1,
    3
  ],
  "specialFeatures": [],
  "cookieMaxAgeSeconds": 33696000,
  "usesCookies": true,
  "cookieRefresh": true,
  "usesNonCookieAccess": true,
  "dataRetention": {
    "stdRetention": 390,
    "purposes": {},
    "specialPurposes": {}
  },
  "urls": [
    {
      "langId": "en",
      "privacy": "https://www.aditude.com/privacy",
      "legIntClaim": "https://www.aditude.com/privacy"
    }
  ],
  "dataDeclaration": [
    1,
    2,
    3,
    4,
    6,
    7,
    8,
    10,
    11
  ],
  "deviceStorageDisclosureUrl": "https://www.aditude.com/storageaccess.json"
```

2024-07-01 07:02 UTC, onkarvhanumante requested changes
@JoshuaMGoldstein, gvl id belongs to `Aditude Inc` and not `cpmstar`

2024-07-01 15:40 UTC, JoshuaMGoldstein commented
> @JoshuaMGoldstein, gvl id belongs to `Aditude Inc` and not `cpmstar`

CPMStar is owned by Aditude Inc.
CPM Star is a DBA/Trademark of Aditude Inc

https://www.globenewswire.com/news-release/2024/03/12/2844707/0/en/Aditude-acquires-Gaming-SSP-CPMStar.html

2024-07-01 17:10 UTC, onkarvhanumante approved these changes

2024-07-22 10:02 UTC, gargcreation1992 approved these changes

2024-07-22 10:02 UTC, merged