New Adapter: AdUp Tech
prebid/prebid-server pull request #4076
Opened 2024-11-26 07:34 UTC by danygielow

Hello,

We as AdUp Technology want to add our own Prebid Server Adapter.
We already have a PrebidJS Adapter.

Docs: https://github.com/prebid/prebid.github.io/pull/5728

2025-01-06 06:11 UTC, danygielow commented on adapters/aduptech/aduptech.go
> +	switch markupType {
What should be changed here? I assume this check is wrong, because we do exactly what the comment suggests.

2025-01-06 16:46 UTC, bsardo commented
@scr-oath can you please review?

2025-01-07 20:50 UTC, scr-oath approved these changes

2025-01-07 20:50 UTC, scr-oath commented on adapters/aduptech/aduptech.go
> +	}
**question**: would a switch on the statusCode (with empty for ok and default clause for this everything-else case) be more readable?

2025-01-07 20:50 UTC, scr-oath commented on adapters/aduptech/aduptech.go
> +	}
**suggestion**: I don't like making copies of the seatbid and bid in a loop
```suggestion
	for i := range response.SeatBid {
		seatBid = &response.SeatBid[i]
		for j := range seatBid.Bid {
			bid := &seatBid.Bid[j]
			bidType, err := getBidType(bid.MType)
			if err != nil {
				errs = append(errs, err)
				continue
			}

			bidResponse.Bids = append(bidResponse.Bids, &adapters.TypedBid{
				Bid:     bid,
				BidType: bidType,
			})
		}
	}
```

2025-01-07 20:50 UTC, scr-oath commented on adapters/aduptech/aduptech.go
> +	switch markupType {
💯 this suggestion (x3?) is not very helpful

2025-01-07 20:50 UTC, scr-oath commented on adapters/aduptech/aduptech_test.go
> +	}
```suggestion
	if buildErr != nil {
		assert.NoError(t, buildErr, "Builder returned unexpected error")
	}
```

2025-01-07 20:50 UTC, scr-oath commented on adapters/aduptech/params_test.go
> +		}
```suggestion
		assert.NoErrorf(t, validator.Validate(openrtb_ext.BidderAdUpTech, json.RawMessage(invalidParam)), "Schema allowed unexpected params: %s", invalidParam)
```

2025-01-08 07:09 UTC, scr-oath requested changes
I didn't mean to approve before… I thought I had ticked request changes…

2025-01-08 07:55 UTC, danygielow commented on adapters/aduptech/aduptech.go
> +		target_currency: "EUR",
Changed to use ExtraAdapterInfo.

2025-01-08 07:56 UTC, danygielow commented on adapters/aduptech/aduptech.go
> +				return nil, err
`convertCurrency` doesn't have to return []error. Refactored to just return a single error.

2025-01-08 07:57 UTC, danygielow commented on adapters/aduptech/aduptech.go
> +	}
Refactored into a switch

2025-01-08 07:57 UTC, danygielow commented on adapters/aduptech/aduptech.go
> +	}
Used your suggestion

2025-01-08 07:57 UTC, danygielow commented on adapters/aduptech/aduptech_test.go
> +	}
Ah, good to know. This is our first time working in Go.

2025-01-08 07:58 UTC, danygielow commented on adapters/aduptech/params_test.go
> +		}
using `assert.Errorf` here, but otherwise used the suggestion.

2025-01-08 08:35 UTC, pm-isha-bharti commented on static/bidder-info/aduptech.yaml
> +  redirect:
@danygielow The usersync URL returned by the /cookie_sync for `aduptech` is currently throwing 404. Can you please check if the URLs added for userSync are correct?

2025-01-08 09:19 UTC, pm-isha-bharti commented on adapters/aduptech/aduptech.go
> +		return nil, nil
Please add a supplemental JSON test where your mock response returns a 204 status code.

2025-01-08 09:22 UTC, pm-isha-bharti commented on adapters/aduptech/aduptech.go
> +		return nil, []error{err}
Please add a supplemental JSON test where your mock response returns a bid response that fails to unmarshal successfully. This can be achieved by setting one of the fields to an incorrect data type.

2025-01-08 09:24 UTC, pm-isha-bharti commented on adapters/aduptech/aduptech.go
> +	case http.StatusBadRequest:
Please add a supplemental JSON test where your mock response returns a 400 status code.

2025-01-08 09:26 UTC, scr-oath commented on adapters/aduptech/aduptech_test.go
> +	}
For what it's worth, I realize you were calling fatal before so I realize you need the require.NoError - assertions from the assert module continue but the test fails whereas those from require halt immediately. This is kind of like google's gtest with its two variants for each assertion so when you can continue you report more/all things that fail but when you can't, you don't.

2025-01-08 18:34 UTC, bsardo commented
Hi @danygielow, @derfryday, now that the review process has begun, can you please push new commits when making changes instead of rebasing and force pushing? It will save reviewers a lot of time when performing delta reviews. All of the commits will be squashed when we merge. Thanks!

2025-01-09 04:39 UTC, scr-oath requested changes

2025-01-09 04:39 UTC, scr-oath commented on adapters/aduptech/aduptech.go
> +		return nil, fmt.Errorf("invalid extra info: %v", err)
**suggestion**: Use `%w` instead - see https://pkg.go.dev/fmt#Errorf

```suggestion
		return nil, fmt.Errorf("invalid extra info: %w", err)
```

2025-01-09 04:39 UTC, scr-oath commented on adapters/aduptech/aduptech.go
> +			imp.BidFloorCur = a.extraInfo.TargetCurrency
**bug?**: There seems like a bug in here somewhere… the converCurrency has a path that can handle errors and, instead, convert to "USD" - how is _that_ choice made here if you always set the BidFloorCur to a.extraInfo.TargetCurrency - should you pass in a pointer to the extraInfo and set the chosen currency in the `convertCurrency` method maybe? or return the choice back and set to that? Style is your choice, but I think that's an unhandled case and might deserve some unit tests to prove it works as intended.

2025-01-09 04:43 UTC, scr-oath commented on adapters/aduptech/aduptech.go
> +		if errors.As(err, &convErr) {
**nitpick/suggestion**: In go, there's a pattern that you try to take the "terminal" case first - return/break/panic/exit so that you don't need an else clause - it saves "cognitive overload" because you can just reason that everything after is the "happy path" - and also saves precious indentation 😄

2025-01-10 07:08 UTC, pm-isha-bharti commented on openrtb_ext/imp_aduptech.go
> +	AdTest    string          `json:"adtest"`
Can we use `bidrequest.test` instead of introducing a separate parameter, considering it is a standard field already used by Prebid?

2025-01-13 12:52 UTC, danygielow commented on adapters/aduptech/aduptech.go
> +			imp.BidFloorCur = a.extraInfo.TargetCurrency
Hi, we try to be ready for the eventuality of conversion rates to EUR not being there for every currency.

The process is:
* first try to convert directly to EUR
* if there is an error, check if it is a conversion rate error
* if it is, try converting to USD first and then from USD to EUR
* So if convertCurrency is successful, then the BidFloorCur is EUR.

There are already special currency conversion JSON tests. See exemplary/simple-banner-convert-currency.json and exemplary/simple-banner-convert-currency-intermediate.json.

2025-01-13 12:54 UTC, danygielow commented on openrtb_ext/imp_aduptech.go
> +	AdTest    string          `json:"adtest"`
Hi,

Unfortunately, we already have this parameter in the Prebid JS Adapter.
See: https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/aduptech.md?plain=1#L26

2025-01-13 12:59 UTC, danygielow commented on adapters/aduptech/aduptech.go
> +		if errors.As(err, &convErr) {
Changed, to have the terminal case first.

2025-01-13 13:05 UTC, danygielow commented on static/bidder-info/aduptech.yaml
> +  redirect:
Fixed sync Endpoint.

2025-01-13 16:33 UTC, scr-oath commented on adapters/aduptech/aduptech.go
> +			imp.BidFloorCur = a.extraInfo.TargetCurrency
oh… so it won't convert to USD and return no error - it would try to go from USD to EUR and return that result - therefore, the `err != nil` would save setting blindly to TargetCurrency even if USD were chosen; thanks

2025-01-13 16:48 UTC, scr-oath commented on adapters/aduptech/aduptech_test.go
> +		Endpoint: "https://example.com/rtb/bid", ExtraAdapterInfo: "{\"target_currency\": \"EUR\"}"}, config.Server{ExternalUrl: "http://hosturl.com", GvlID: 1, DataCenter: "2"})
**suggestion**: json can be easier to read/maintain if using the backtick string literal (See https://go.dev/ref/spec#String_literals). Also… a few newlines couldn't hurt here to line up the fields so you can tell what goes with what at a glance:

```suggestion
	bidder, buildErr := Builder(
		openrtb_ext.BidderAdUpTech,
		config.Adapter{
			Endpoint: "https://example.com/rtb/bid",
			ExtraAdapterInfo: `{"target_currency": "EUR"}`,
		},
		config.Server{ExternalUrl: "http://hosturl.com", GvlID: 1, DataCenter: "2"},
	)
```

2025-01-13 16:50 UTC, scr-oath commented on adapters/aduptech/aduptech_test.go
> +		Endpoint: "https://example.com/rtb/bid", ExtraAdapterInfo: "{\"target_currency\": \"EUR\"}"}, config.Server{ExternalUrl: "http://hosturl.com", GvlID: 1, DataCenter: "2"})
There are other places where this pattern can improve readability; I've only exemplified this one.

2025-01-16 07:54 UTC, danygielow commented on adapters/aduptech/aduptech_test.go
> +		Endpoint: "https://example.com/rtb/bid", ExtraAdapterInfo: "{\"target_currency\": \"EUR\"}"}, config.Server{ExternalUrl: "http://hosturl.com", GvlID: 1, DataCenter: "2"})
OK, sorry, i thought gofmt takes care of everything. I didn't even try to format anything.
I come from Python where black or now ruff-format will also take care of line breaks and indentations in appropriate places to improve readability. And they reference gofmt as an inspiration.

2025-01-21 08:35 UTC, danygielow commented
@scr-oath The checks seem to run have problems. Can you please take a look.

2025-01-21 15:37 UTC, scr-oath commented
> @scr-oath The checks seem to have problems. Can you please take a look.

Hmm… I still see checks running and none of the completed ones have failed - will check back when those finish

2025-01-21 17:38 UTC, scr-oath commented on adapters/aduptech/aduptech.go
> +		return nil, fmt.Errorf("invalid extra info: TargetCurrency is empty, pls check")
**nitpick** (not-blocking) while a little pedantic, I prefer errors.New for errors that are just string literals.
```suggestion
		return nil, errors.New("invalid extra info: TargetCurrency is empty, pls check")
```

2025-01-21 19:16 UTC, bsardo commented on adapters/aduptech/aduptech.go
> +	}
Please use the adapter utility functions `IsResponseStatusCodeNoContent` and `CheckResponseStatusCodeForErrors` found in `adapters/response.go` for processing the http status code.

2025-01-21 19:25 UTC, bsardo commented on adapters/aduptech/aduptech.go
> +	switch markupType {
I'm not sure why this is triggering but you can ignore it.

2025-01-22 12:37 UTC, danygielow commented on adapters/aduptech/params_test.go
> +	`{ "publisher": "123456789", "placement": "234567890", "query": "test" }`,
added minLength to publisher and placement, added more params tests

2025-01-22 12:37 UTC, danygielow commented on adapters/aduptech/aduptech.go
> +		}
added test

2025-01-22 12:38 UTC, danygielow commented on adapters/aduptech/aduptech.go
> +		return nil, fmt.Errorf("invalid extra info: TargetCurrency is empty, pls check")
makes sense, changed it

2025-01-22 20:45 UTC, bsardo commented on static/bidder-info/aduptech.yaml
> +  email: "support@adup-tech.com"
👍 email received.

2025-01-24 19:16 UTC, bsardo commented on adapters/aduptech/aduptech.go
> +		}
Ah yes I understand but I'm just concerned with testing your adapter. We can force an intermediate currency conversion failure so that we achieve code coverage of this error block, though my suggested approach is incorrect. Instead you can use this test:
[currency-conversion-intermediate-failure.json](https://github.com/user-attachments/files/18540712/currency-conversion-intermediate-failure.json)

2025-01-24 19:19 UTC, bsardo reviewed
This is looking good. I just have one last request in this [comment](https://github.com/prebid/prebid-server/pull/4076#discussion_r1929132040).

2025-01-27 11:51 UTC, danygielow commented on adapters/aduptech/aduptech.go
> +		}
OK, added that test. Thank you

2025-01-27 15:58 UTC, bsardo submitted a review, later dismissed

2025-01-28 05:35 UTC, danygielow commented on adapters/aduptech/aduptech.go
> +	}
Hi, it is not the same `currency` library, and ParseISO also returns a `currency.Unit`.
So I adapted your suggestion and added a corresponding test.

2025-01-28 22:28 UTC, guscarreon reviewed
I'm ready to approve. I just have a suggestion about the error messages mentioned below that would be fairly straightforward to implement if you want. Let me know. I'll approve either way.

2025-01-28 22:28 UTC, guscarreon commented on adapters/aduptech/aduptechtest/supplemental/currency-conversion-failure.json
> +      "value": "Currency conversion rate not found: 'USD' => 'EUR'",
Nitpick: I don't oppose this error message if you find it useful, but wouldn't `"Converted currency of bid floor from 'AUD' to 'USD' but there was an error converting from 'USD' to 'EUR': Currency conversion rate not found: 'USD' => 'EUR'"` be more accurate? We could tweak the `convertCurrency` function to get a more descriptive message:
```
 87   func (a *adapter) convertCurrency(value float64, cur string, reqInfo *adapters.ExtraRequestInfo) (float64, error) {
 88       convertedValue, err := reqInfo.ConvertCurrency(value, cur, a.extraInfo.TargetCurrency)
 89
 90       if err != nil {
 91           var convErr prebidcurrency.ConversionNotFoundError
 92           if !errors.As(err, &convErr) {
 93               return 0, err
 94           }
 95
 96           // try again by first converting to USD
 97           // then convert to target_currency
 98           convertedValue, err = reqInfo.ConvertCurrency(value, cur, "USD")
 99
100           if err != nil {
101 -             return 0, err
    +             return 0, fmt.Errorf("Currency conversion rate not found from '%s' to '%s'. Error converting from '%s' to 'USD': %w", cur, a.extraInfo.TargetCurrency, cur, err)
102           }
adapters/aduptech/aduptech.go
```

2025-01-28 22:28 UTC, guscarreon commented on adapters/aduptech/aduptechtest/supplemental/currency-conversion-intermediate-failure.json
> +        "value": "Currency conversion rate not found: 'AUD' => 'USD'",
Nitpick: I don't oppose this error message if you find it useful, but wouldn't `"Currency conversion rate not found from 'AUD' to 'EUR'. Error converting from 'AUD' to 'USD': Currency conversion rate not found: 'AUD' => 'USD'"` be more accurate? We could tweak the `convertCurrency` function to get a more descriptive message:
```
104           convertedValue, err = reqInfo.ConvertCurrency(convertedValue, "USD", a.extraInfo.TargetCurrency)
105
106           if err != nil {
107 -             return 0, err
    +             return 0, fmt.Errorf("Currency conversion rate not found from '%s' to '%s'. Error converting from '%s' to 'USD': %w", cur, a.extraInfo.TargetCurrency, cur, err)
108           }
109       }
110       return convertedValue, nil
111   }
112
adapters/aduptech/aduptech.go
```

2025-01-29 05:51 UTC, danygielow commented on adapters/aduptech/aduptechtest/supplemental/currency-conversion-failure.json
> +      "value": "Currency conversion rate not found: 'USD' => 'EUR'",
I agree, I changed the error message.

2025-01-29 05:51 UTC, danygielow commented on adapters/aduptech/aduptechtest/supplemental/currency-conversion-intermediate-failure.json
> +        "value": "Currency conversion rate not found: 'AUD' => 'USD'",
I agree, I changed the error message.

2025-01-29 14:49 UTC, bsardo approved these changes

2025-01-30 17:14 UTC, merged