New Adapter: Pixfuture
prebid/prebid-server pull request #4117
Opened 2024-12-19 15:23 UTC by pixfuture-media

This Pixfuture Prebid Server Adapter enables seamless integration with Pixfuture's ad exchange, allowing publishers to leverage their demand through server-side header bidding. The adapter formats outgoing bid requests, processes incoming bid responses, and adheres to OpenRTB standards for efficient and privacy-compliant ad delivery.

2024-12-19 18:29 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +	bidder := &PixfutureAdapter{
This is fixed!

2024-12-24 09:40 UTC, gargcreation1992 commented on adapters/pixfuture/pixfuture.go
> +	}
This check is not required here as this is being checked in the core codebase already. Here is the link - https://github.com/prebid/prebid-server/blob/32fdbc4be35375912ac886ca05f7318c06995e0c/endpoints/openrtb2/auction.go#L770-L772

2024-12-24 09:48 UTC, gargcreation1992 commented on adapters/pixfuture/pixfuture.go
> +	}
This is correct but you could also use the common code as below - 
```
if adapters.IsResponseStatusCodeNoContent(responseData) {
		return nil, nil
}

if err := adapters.CheckResponseStatusCodeForErrors(responseData); err != nil {
		return nil, []error{err}
}

2024-12-24 09:55 UTC, gargcreation1992 commented on static/bidder-info/pixfuture.yaml
> +  email: "client-support@pixfuture.com"
Sent an email for verification. Please reply with "received".

2024-12-27 14:10 UTC, pixfuture-media commented
received

On Tue, 24 Dec 2024 at 04:56, Ashish Garg ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In static/bidder-info/pixfuture.yaml
> <https://github.com/prebid/prebid-server/pull/4117#discussion_r1896610621>
> :
>
> > @@ -0,0 +1,16 @@
> +endpoint: "https://srv-adapter.pixfuture.com/pixservices"
> +maintainer:
> +  email: ***@***.***"
>
> Sent an email for verification. Please reply with "received".
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/prebid/prebid-server/pull/4117#pullrequestreview-2521760813>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUDNEQT5OAVWPASNEC4GV732HEVTPAVCNFSM6AAAAABT5HIYBCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRRG43DAOBRGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-07 19:48 UTC, pixfuture-media commented
I would like to ask for your help with reviewing a pull request  [New Adapter: Pixfuture #4117]. 
Your feedback would be greatly appreciated.   
When do you think you might be able to review this?  
Thank you in advance for your time and effort.

2025-01-17 15:20 UTC, bretg commented
@pixfuture-media - please address the review comments above. Then the reviewer will look at this PR again.

2025-01-17 16:40 UTC, pixfuture-media commented
Please review the Pixfuture adapter and let us know if any further actions are required.

2025-01-22 19:28 UTC, bsardo commented
@scr-oath can you please review?

2025-01-24 14:49 UTC, pixfuture-media commented
> @scr-oath can you please review?

Please provide the next steps from our side. We've implemented all the requested changes.

2025-01-28 14:40 UTC, pixfuture-media commented
Hi, @gargcreation1992. Please let us know what is required from our end.

2025-01-29 20:44 UTC, bsardo reviewed
See my comments. For reference, we have a [section](https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html) in the developer docs that describe how to build and test a Go adapter. LMK if you have any questions.

2025-01-29 20:44 UTC, bsardo commented on docs/pixfuture.md
Delete this file and instead open a docs PR in the [docs repo](https://github.com/prebid/prebid.github.io) to update your adapter documentation. It looks like you already have a [page](https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/pixfuture.md) so it just needs to be updated.

2025-01-29 20:44 UTC, bsardo commented on exchange/adapter_builders.go
> +		openrtb_ext.BidderPixfuture:         pixfuture.Builder,
Move this elsewhere in the list so we maintain alphabetical order.

2025-01-29 20:44 UTC, bsardo commented on openrtb_ext/bidders.go
> +	BidderPixfuture,
Move this elsewhere in the list so we maintain alphabetical order.

2025-01-29 20:44 UTC, bsardo commented on openrtb_ext/bidders.go
> +	BidderPixfuture         BidderName = "pixfuture"
Move this elsewhere in the list so we maintain alphabetical order.

2025-01-29 20:44 UTC, bsardo commented on adapters/pixfuture/params_test.go
Please see the developer docs [Test Your Adapter section](https://docs.prebid.org/prebid-server/developers/add-new-bidder-go.html#test-your-adapter) on how to test your adapter. All coverage should be achieved using the JSON test framework wherever possible.

2025-01-29 20:44 UTC, bsardo commented on adapters/pixfuture/params_test.go
> +}
You can delete all of this.

2025-01-29 20:44 UTC, bsardo commented on static/bidder-params/pixfuture.json
> +
Remove blank line.

2025-01-29 20:44 UTC, bsardo commented on static/bidder-params/pixfuture.json
> +
Remove blank line.

2025-01-29 20:44 UTC, bsardo commented on static/bidder-params/pixfuture.json
> +      }
Is an empty string `pix_id` considered valid? If not, add a `minLength` field to the `pix_id` object here.

2025-01-29 20:44 UTC, bsardo commented on static/bidder-info/pixfuture.yaml
> +endpoint: "https://srv-adapter.pixfuture.com/pixservices"
Verified endpoint is reachable
```
curl -i --location --request POST https://srv-adapter.pixfuture.com/pixservices
HTTP/2 400
date: Wed, 29 Jan 2025 20:24:37 GMT
content-type: text/plain; charset=utf-8
content-length: 46
access-control-allow-origin:
cache-control: no-cache, no-store, must-revalidate
expires: 0
pragma: no-cache
vary: Origin
x-prebid: pbs-go/unknown
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=RkSwUSKVpXRcuQgGsoXAvviqL5GfXFGw3YzlRzaQLquDNQ8fbQC7lj0tYCyKLhUqSSEIUDhe%2FSF4WXRFKKh5mHyOcE%2BB5IICOn1CHgRqNWoYIJblpTUXQttAfBggc5KfFN4v6Qa7px3u9Y4%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 909bf2620fa332dc-EWR
server-timing: cfL4;desc="?proto=TCP&rtt=10662&min_rtt=8902&rtt_var=4125&sent=7&recv=11&lost=0&retrans=0&sent_bytes=2914&recv_bytes=611&delivery_rate=275510&cwnd=252&unsent_bytes=0&cid=23304c355b4fda57&ts=80&x=0"

Invalid request: unexpected end of JSON input
```

2025-01-29 20:44 UTC, bsardo commented on static/bidder-info/pixfuture.yaml
> +  email: "client-support@pixfuture.com"
I resent this email. Please reply to it with "received" for verification.

2025-01-29 20:44 UTC, bsardo commented on static/bidder-info/pixfuture.yaml
> +gvlVendorID: 839
Verified GVL ID
```
curl https://vendor-list.consensu.org/v3/vendor-list.json | jq '.vendors."839"'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  658k  100  658k    0     0  3917k      0 --:--:-- --:--:-- --:--:-- 3922k
{
  "id": 839,
  "name": "PixFuture Media Inc.",
  "purposes": [
    2,
    7,
    10
  ],
  "legIntPurposes": [],
  "flexiblePurposes": [],
  "specialPurposes": [
    1,
    2,
    3
  ],
  "features": [],
  "specialFeatures": [
    1,
    2
  ],
  "cookieMaxAgeSeconds": 604800,
  "usesCookies": true,
  "cookieRefresh": false,
  "urls": [
    {
      "langId": "en",
      "privacy": "https://www.pixfuture.com/terms-and-conditions#privacy-policy",
      "legIntClaim": "https://www.pixfuture.com/terms-and-conditions#dpa-terms"
    }
  ],
  "usesNonCookieAccess": true,
  "dataRetention": {
    "stdRetention": 30,
    "purposes": {
      "2": 7,
      "7": 365,
      "10": 365
    },
    "specialPurposes": {}
  },
  "dataDeclaration": [
    1,
    2,
    3,
    8,
    9,
    11
  ],
  "deviceStorageDisclosureUrl": "https://pixfuture.com/vendor-disclosures.json"
}
```

2025-01-29 20:44 UTC, bsardo commented on static/bidder-info/pixfuture.yaml
> +    url: "https://sync.pixfuture.com/sync?gdpr={{.GDPR}}&consent={{.GDPRConsent}}&us_privacy={{.USPrivacy}}&redirect={{.RedirectURL}}"
I'm getting an error that this does not resolve to a known resource. My test url is `https://sync.pixfuture.com/sync?gdpr=0&consent=CQL_D2nQL_D2nPjAAAENCZCAAP_AAH_AAAAAGGwAQGGgYbABAYaAAA.II7Nd_X__bX9n-_7_6ft0eY1f9_r37uQzDhfNs-8F3L_W_LwX32E7NF36tq4KmR4ku1bBIQNtHMnUDUmxaolVrzHsak2cpyNKJ_JkknsZe2dYGF9Pn9lD-YKZ7_5_9_f52T_9_9_-39z3_9f___dv_-__-vjf_599n_v9fV_78_Kf9______-____________8A&us_privacy=&redirect=http%3A%2F%2Flocalhost%3A8000%2Fsetuid%3Fbidder%3Dpixfuture%26gdpr%3D0%26gdpr_consent%3DCQL_D2nQL_D2nPjAAAENCZCAAP_AAH_AAAAAGGwAQGGgYbABAYaAAA.II7Nd_X__bX9n-_7_6ft0eY1f9_r37uQzDhfNs-8F3L_W_LwX32E7NF36tq4KmR4ku1bBIQNtHMnUDUmxaolVrzHsak2cpyNKJ_JkknsZe2dYGF9Pn9lD-YKZ7_5_9_f52T_9_9_-39z3_9f___dv_-__-vjf_599n_v9fV_78_Kf9______-____________8A%26gpp%3D%26gpp_sid%3D%26f%3Di%26uid%3D`

2025-01-29 20:44 UTC, bsardo commented on adapters/pixfuture/pixfuture.go
> +		}
This validation check is not needed since you've only declared support for banner and video in your YAML file and PBS core will only call your adapter if it contains media types you declare support for.

2025-01-29 20:44 UTC, bsardo commented on adapters/pixfuture/pixfuture.go
> +	}
This validation logic can be removed as your adapter will only be called if it contains at least one impression.

2025-01-29 20:44 UTC, bsardo commented on adapters/pixfuture/pixfuture.go
> +		Method: "POST",
I suggest using `http.MethodPost` instead of `"POST"`.

2025-01-29 20:44 UTC, bsardo commented on adapters/pixfuture/pixfuture.go
> +			//seatBid.Bid[i].MType = mType
Delete the commented out code.

2025-01-30 02:29 UTC, bsardo commented on static/bidder-info/pixfuture.yaml
> +  email: "client-support@pixfuture.com"
Confirmed receipt.

2025-01-30 18:49 UTC, scr-oath requested changes

2025-01-30 18:49 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +		errs = append(errs, fmt.Errorf("failed to marshal bid request: %v", err))
**suggestion**: when formatting an err within another error, always use the wrap directive (`%w`)
```suggestion
		errs = append(errs, fmt.Errorf("failed to marshal bid request: %w", err))
```
- See https://pkg.go.dev/fmt#Errorf

2025-01-30 22:18 UTC, pixfuture-media commented on static/bidder-info/pixfuture.yaml
> +    url: "https://sync.pixfuture.com/sync?gdpr={{.GDPR}}&consent={{.GDPRConsent}}&us_privacy={{.USPrivacy}}&redirect={{.RedirectURL}}"
The sync URL has been fixed

2025-01-31 14:51 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		errs = append(errs, fmt.Errorf("no valid impressions in bid request"))
Updated as per your suggestion.

2025-01-31 14:51 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +			//seatBid.Bid[i].MType = mType
Updated as per your suggestion.

2025-01-31 14:51 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		Method: "POST",
Updated as per your suggestion.

2025-01-31 14:51 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +	}
Updated as per your suggestion.

2025-01-31 14:52 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		}
Updated as per your suggestion.

2025-01-31 14:59 UTC, pixfuture-media commented on config/config.go
> +	v.SetDefault("gdpr.timeouts_ms.active_vendorlist_fetch", 30000)
Changes have been reverted.

2025-01-31 17:22 UTC, scr-oath commented
> > @scr-oath can you please review?
> 
> Please provide the next steps from our side. We've implemented all the requested changes.

I still see a bunch of unresolved comments from @bsardo … we can leave the bot-generated comments unresolved, but I would like to re-review after others' comments are addressed (I don't think there's process to promote my RFC to at least neutral… wish there was like an "I approve but defer to others" or the like feature in github - there used to be something like that in gerrit when I used that years and years ago, and I miss it 😉  )

Anyway… will re-review when those are tackled

2025-01-31 17:45 UTC, pixfuture-media commented
@scr-oath Apologies for any confusion. I'll review what hasn't been addressed yet and respond to @bsardo accordingly.

2025-01-31 18:27 UTC, pixfuture-media commented on docs/pixfuture.md
This files removed

2025-01-31 18:37 UTC, pixfuture-media commented on openrtb_ext/bidders.go
> +	BidderPixfuture,
The "BidderPixfuture," in the openrtb_ext/bidders.go have been moved to alphabetical order.

2025-01-31 18:39 UTC, pixfuture-media commented on static/bidder-params/pixfuture.json
> +
The blank line have been removed

2025-01-31 18:43 UTC, pixfuture-media commented on static/bidder-params/pixfuture.json
> +      }
The "minLength": 3" have been added.

2025-01-31 18:45 UTC, pixfuture-media commented on static/bidder-info/pixfuture.yaml
> +endpoint: "https://srv-adapter.pixfuture.com/pixservices"
The endpoint have been fixed to "https://sync.pixfuture.com/cookiesync"

2025-01-31 19:27 UTC, scr-oath commented on go.mod
> +	github.com/golang/glog v1.2.4
Can you merge the origin into this? I believe this change was already done in previous commit #4182

2025-02-02 18:46 UTC, scr-oath commented
> @scr-oath Apologies for any confusion. I'll review what hasn't been addressed yet and respond to @bsardo accordingly.

Also, I see one dangling comment from me still https://github.com/prebid/prebid-server/pull/4117#discussion_r1937810771 

I see that you have merged a few times, maybe once more would remove that diff from the go.mod/sum?

2025-02-03 18:42 UTC, pixfuture-media commented on go.mod
> +	github.com/golang/glog v1.2.4
Yes, it was already done in previous commit

2025-02-03 18:57 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture_test.go
Test JSONs have been reviewed and edited.

2025-02-03 18:59 UTC, pixfuture-media commented on adapters/pixfuture/testdata/valid-bid-request.json
The developer has been  recreated in adapters/pixfuture/pixfuturetest/exemplary and adapters/pixfuture/pixfuturetest/supplemental

2025-02-04 20:19 UTC, pixfuture-media commented on go.mod
> +	github.com/golang/glog v1.2.4
go.mod updated and  in right state now

2025-02-04 21:13 UTC, scr-oath commented on go.mod
> +	github.com/golang/glog v1.2.4
![image](https://github.com/user-attachments/assets/07768c32-9bed-4f43-acef-ee297767d519)

Why does this show a change in YOUR PR?

2025-02-04 21:22 UTC, scr-oath requested changes

2025-02-04 21:22 UTC, scr-oath commented on go.mod
> +	github.com/golang/glog v1.2.4
Hmm… I can't reopen that comment, so I'll try again, if you merge, you will not see that change in your PR.

After
```
git merge origin/master
```
I see the following different merge-bases, showing that your fork is not merged with the latest.

```
(oath_tools) [scr@MacBook-Pro-3]$ git merge-base origin/master pixfuture-media/master
243c0f06f0f9ea2cb6cf0994dc7791ae63e957ed
(oath_tools) [scr@MacBook-Pro-3]$ git merge-base origin/master HEAD
f2d62efa4f0336185a22fff1ff31bab5cea53162
```

2025-02-11 19:58 UTC, guscarreon commented on go.mod
> +)
This file seems to have slight, inconsequential format change with respect to `master`. Can you bring `master`'s version so we don't have this change listed here?
```
$ git checkout --patch master go.mod
```

2025-02-11 19:58 UTC, guscarreon commented on go.sum
> +rsc.io/sampler v1.3.0/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=
This file seems to have slight, inconsequential format change with respect to `master`. Can you bring `master`'s version so we don't have this change listed here?
```
$ git checkout --patch master go.sum
```

2025-02-11 19:58 UTC, guscarreon commented on coverage.out
> +github.com/prebid/prebid-server/v3/adapters/pixfuture/pixfuture.go:103.2,103.28 1 1
There's no need to incorporate this file into our repository. Can you please delete `coverage.out`?

2025-02-13 16:08 UTC, bsardo commented on static/bidder-params/pixfuture.json
> +
Please remove the blank line.

2025-02-13 16:26 UTC, bsardo commented on static/bidder-info/pixfuture.yaml
> +    url: "https://sync.pixfuture.com/sync?gdpr={{.GDPR}}&consent={{.GDPRConsent}}&us_privacy={{.USPrivacy}}&redirect={{.RedirectURL}}"
I'm now using `https://sync.pixfuture.com/cookiesync?gdpr=0&consent=CQMq_pHQMq_pHCJAAAENCZCAAP_AAH_AAAAABzwAQBzgHPABAHOAAA.II7Nd_X__bX9n-_7_6ft0eY1f9_r37uQzDhfNs-8F3L_W_LwX32E7NF36tq4KmR4ku1bBIQNtHMnUDUmxaolVrzHsak2cpyNKJ_JkknsZe2dYGF9Pn9lD-YKZ7_5_9_f52T_9_9_-39z3_9f___dv_-__-vjf_599n_v9fV_78_Kf9______-____________8A&us_privacy=&redirect=http%3A%2F%2Flocalhost%3A8000%2Fsetuid%3Fbidder%3Dpixfuture%26gdpr%3D0%26gdpr_consent%3DCQMq_pHQMq_pHCJAAAENCZCAAP_AAH_AAAAABzwAQBzgHPABAHOAAA.II7Nd_X__bX9n-_7_6ft0eY1f9_r37uQzDhfNs-8F3L_W_LwX32E7NF36tq4KmR4ku1bBIQNtHMnUDUmxaolVrzHsak2cpyNKJ_JkknsZe2dYGF9Pn9lD-YKZ7_5_9_f52T_9_9_-39z3_9f___dv_-__-vjf_599n_v9fV_78_Kf9______-____________8A%26gpp%3D%26gpp_sid%3D%26f%3Di%26uid%3D`.

The cookie sync endpoint is now reachable using your revised url but your sync will not be allowed as currently designed.

For a sync of type `redirect`, the specific rule it's breaking is that you MUST end up redirecting to the PBS host company's /setuid endpoint.
If you want to make this of type `iframe` instead you MUST end up calling the PBS host company's /setuid endpoint.

In the iframe case we would tolerate syncing a reasonable number of DSPs, the current guidance is 10, but no SSPs.

@bretg anything you want to add here?

2025-02-13 16:30 UTC, bsardo commented on adapters/pixfuture/pixfuture.go
> +		}
The validation check still exists.

2025-02-13 18:13 UTC, bretg commented on static/bidder-info/pixfuture.yaml
> +    url: "https://sync.pixfuture.com/sync?gdpr={{.GDPR}}&consent={{.GDPRConsent}}&us_privacy={{.USPrivacy}}&redirect={{.RedirectURL}}"
@pixfuture-media - your sync has to end up calling the host PBS /setuid or it's not going to be allowed.

2025-02-14 18:50 UTC, pixfuture-media commented on go.mod
> +)
fixed

2025-02-14 18:50 UTC, pixfuture-media commented on static/bidder-params/pixfuture.json
> +	"minLength": 3
Fixed

2025-02-14 18:50 UTC, pixfuture-media commented on openrtb_ext/imp_pixfuture.go
> +	PlacementID string `json:"pix_id"`
fixed

2025-02-14 18:51 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +	}
fixed

2025-02-14 18:53 UTC, pixfuture-media commented on go.sum
> +rsc.io/sampler v1.3.0/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=
fixed

2025-02-14 18:53 UTC, pixfuture-media commented on coverage.out
> +github.com/prebid/prebid-server/v3/adapters/pixfuture/pixfuture.go:103.2,103.28 1 1
fixed

2025-02-19 15:15 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/supplemental/bid_parsing_error.json
it haas been fixed

2025-02-19 15:32 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/supplemental/bid_parsing_error.json
its already implemented

2025-02-24 21:41 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/exemplary/simple-banner.json
Issues with RunJSONBidderTes and JSON tests resolved

2025-03-03 19:39 UTC, bretg commented
docs PR https://github.com/prebid/prebid.github.io/pull/5915

2025-03-05 13:54 UTC, pixfuture-media commented
Hello Bretg,
I hope you are well.
Please let me know the next steps required from my side.
Vitali I.

2025-03-05 14:20 UTC, bretg commented
Requesting re-review from @bsardo and @guscarreon

2025-03-11 16:33 UTC, bsardo commented on adapters/pixfuture/pixfuturetest/exemplary/valid.json
Please rename to `banner.json`

2025-03-14 19:02 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/exemplary/valid.json
Renamed

2025-03-14 19:02 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/exemplary/valid.json
> +                    "placementId": "456"
added

2025-03-14 19:05 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture_test.go
> +}
Removed and changedwith the JSON test framework

2025-03-14 19:05 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture_test.go
> +}
Removed and changedwith the JSON test framework

2025-03-14 19:06 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +			bidType, err := getMediaTypeForBid(bid)
Changed via different concept

2025-03-14 20:08 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		return nil, []error{err}
Created a bad_status.json

2025-03-14 20:10 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		return nil, []error{err}
Added:
missing_params.json
no_banner.json
no_bids.json
no_content.json
no_impressions.json
unknown_type.json

2025-03-14 20:10 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +	}
Removed

2025-03-14 20:12 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +	}
Channged.

2025-03-17 17:03 UTC, pixfuture-media commented
I've addressed all the requested changes on my end. Could you please review it and let me know the next steps?
Thank you!

2025-03-17 18:14 UTC, scr-oath requested changes

2025-03-17 18:14 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +		}
**suggestion**: move this out to a struct in openrtb_ext
https://git.ouryahoo.com/monetization/prebid-server/tree/main/openrtb_ext

Actually… @bsardo - can you help me with the organization - where should these go? What ext thing is this - I already see that this PR has an imp_pixfuture but that doesn't contain this bidder.pix_id field…

2025-03-17 18:14 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +		if err := json.Unmarshal(imp.Ext, &ext); err != nil {
**suggestion**: use jsonutil - encoding/json is much much slower than the choice(s) made in the jsonutil

2025-03-17 18:14 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +		reqJSON, err := json.Marshal(request)
**suggestion**: Use jsonutil

2025-03-17 18:14 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +			Method:  "POST",
**nitpick**: Use `http.MethodPost`
```suggestion
			Method:  http.MethodPost,
```

2025-03-17 18:14 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +	}
This can use the ext definition in `openrtb_ext`

2025-03-17 18:14 UTC, scr-oath commented on adapters/pixfuture/pixfuture_test.go
> +}
**suggestion**: You shouldn't need this, there is a generic solution in ptrutil.ToPtr
https://github.com/prebid/prebid-server/blob/master/util/ptrutil/ptrutil.go#L3-L5

2025-03-17 18:14 UTC, scr-oath commented on adapters/pixfuture/pixfuture_test.go
> +	}
**suggestion**: prefer the testify assert or require.

```suggestion
	require.NoError(t, buildErr, "Builder returned unexpected error")
```

2025-03-17 18:14 UTC, scr-oath commented on adapters/pixfuture/pixfuture_test.go
> +			}
```suggestion
			require.NoErrorf(t, err, "Failed to glob JSON files in %s", dir)
```

2025-03-17 18:14 UTC, scr-oath commented on adapters/pixfuture/pixfuture_test.go
> +					}
```suggestion
					require.NoError(t, err, "Failed to create temp dir")
```

2025-03-17 18:14 UTC, scr-oath commented on adapters/pixfuture/pixfuture_test.go
> +					}
```suggestion
					require.NoErrorf(t, ioutil.WriteFile(dst, input, 0644), "Failed to write %s", dst)
```

2025-03-17 18:14 UTC, scr-oath commented on adapters/pixfuture/pixfuture_test.go
> +					if err := ioutil.WriteFile(dst, input, 0644); err != nil {
**suggestion**: I think that this method is deprecated and os.WriteFile is preferred
```suggestion
					if err := os.WriteFile(dst, input, 0644); err != nil {
```

2025-03-17 20:47 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +	for _, imp := range request.Imp {
refactored

2025-03-17 20:49 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		}
I used an alternative  - Local Named Struct:
type PixfutureExt struct {
    Bidder struct {
        PixID string `json:"pix_id"`
    } `json:"bidder"`
}
Then use var ext PixfutureExt in MakeRequests. This is less ideal but keeps it within the adapter’s scope.

2025-03-17 20:50 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		if err := json.Unmarshal(imp.Ext, &ext); err != nil {
refactored by use  jsonutil

2025-03-17 20:51 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture_test.go
> +			}
refactored to use require......

2025-03-17 20:52 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture_test.go
> +					}
refactored ti uuse require......

2025-03-17 20:52 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture_test.go
> +					}
refactored to use require....

2025-03-17 20:53 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture_test.go
> +					}
refactored to use require...

2025-03-17 20:53 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture_test.go
> +					if err := ioutil.WriteFile(dst, input, 0644); err != nil {
fixed

2025-03-17 20:55 UTC, pixfuture-media commented
I've addressed all the requested changes on my end. Could you please review it and let me know the next steps?
Thank you!

2025-03-24 17:53 UTC, bsardo commented on coverage.out
Please delete this file.

2025-03-24 18:15 UTC, pixfuture-media commented on coverage.out
Hello bsardo,
Its deleted already

2025-04-01 18:46 UTC, guscarreon reviewed
Please remove `coverage.out` as this file doesn't need to make it into the codebase. Please also rollback changes to `go.mod` and `go.sum` as those changes are not related to your adapter.

2025-04-01 18:46 UTC, guscarreon commented on adapters/pixfuture/pixfuturetest/supplemental/no_content.json
> +{
Can we rename this file to `adapters/pixfuture/pixfuturetest/supplemental/empty_response_body.json`?

2025-04-01 18:46 UTC, guscarreon commented on adapters/pixfuture/pixfuture.go
> +		} `json:"prebid"`
Other bidders specify their media type either in `seatbid[i].bid[j].mtype`, which is recommended:
```
     "seatbid": [
       {
         "bid": [
           {
             "id": "bid1",
             "impid": "imp1",
             "mtype":"banner"
           }
         ]
       }
     ]
```
Or they simply `nil` check the `Banner`, `Video`, `Native` and `Audio` to determine the media type. Will Pixfuture use `seatbid[i].bid[j].ext` for this? If yes, we're fine with this approach.

2025-04-02 15:29 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		PixID string `json:"pix_id"`
This code section has been refactored and successfully tested based on @guscarreon's recommendation.

2025-04-02 15:29 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +var jsonIter = jsoniter.ConfigCompatibleWithStandardLibrary
This code section has been refactored and successfully tested based on @guscarreon's recommendation.

2025-04-02 15:30 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +			errs = append(errs, &errortypes.BadInput{Message: "Invalid impression extension"})
This code section has been refactored and successfully tested based on @guscarreon's recommendation.

2025-04-02 15:30 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +			errs = append(errs, &errortypes.BadInput{Message: "Banner, Native, or Video impression required"})
This code section has been refactored and successfully tested based on @guscarreon's recommendation.

2025-04-02 15:31 UTC, pixfuture-media commented on static/bidder-info/pixfuture.yaml
> +      - video
This code section has been refactored and successfully tested based on @guscarreon's recommendation.

2025-04-02 15:31 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		} `json:"prebid"`
This code section has been refactored and successfully tested based on @guscarreon's recommendation.

2025-04-02 15:31 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/supplemental/no_content.json
> +{
This code section has been refactored and successfully tested based on @guscarreon's recommendation.

2025-04-02 16:08 UTC, pixfuture-media commented
Please review the latest refactored version of Pixfuture Adapter and let us know if any further adjustments are needed.

2025-04-03 17:02 UTC, guscarreon reviewed
Please remove file `coverage.out` as it doesn't need to be added to our repository.

2025-04-10 15:47 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture_test.go
> +	for _, dir := range dirs {
The loop has been removed from TestJsonSamples. Additionally, updates have been made to missing_params.json and pixfuturetest/supplemental/no_banner.json.

2025-04-16 03:49 UTC, guscarreon reviewed
It's looking good. I left a couple of comments below and I'd also like to invite you again to please roll back the changes to `go.mod` and `go.sum` and to get rid of `coverage.out` as it is a very big 55,000 line file that is not necessary to merge to the master branch. Thank you.

2025-04-16 03:49 UTC, guscarreon commented on adapters/pixfuture/pixfuture.go
> +		return openrtb_ext.BidTypeNative, nil
Given that `static/bidder-info/pixfuture.yaml` doesn't list `native` as a supported type, no `request.Imp` elements with a non-nil `request.Imp[i].Native` will get to `MakeRequests()` and no native-media requests will be sent to your bid server. Do you want to list `native` as a supported media type in `static/bidder-info/pixfuture.yaml`?
```
 5   capabilities:
 6     site:
 7       mediaTypes:
 8         - banner
 9         - video
   +       - native
10     app:
11       mediaTypes:
12         - banner
13         - video
   +       - native
14   userSync:
static/bidder-info/pixfuture.yaml
```

2025-04-16 03:49 UTC, guscarreon commented on adapters/pixfuture/pixfuture.go
> +		if err := jsonutil.Unmarshal(imp.Ext, &bidderExt); err != nil {
Lines 37 to 49 unmarshal values into `bidderExt` and `ext`, but we don't seem to do anything with them afterwards. If the intent behind these lines of code is to unmarshal in order to validate every `imp[i].ext.bidder` field, there's no need. Prebid Server validates all of these upstream before passing them in the `request` argument of `MakeRequests()`. Therefore, the `return` statements in lines 39 and 46 are basically logically dead code unless the system runs out of memory or something very particular happens which is somewhat unlikely. These could, if you agree, be removed: 
```
33     for i := range request.Imp {
34         imp := &request.Imp[i]
35
36 -       // Log raw imp.Ext for debugging
37 -       var bidderExt adapters.ExtImpBidder
38 -       if err := jsonutil.Unmarshal(imp.Ext, &bidderExt); err != nil {
39 -           return nil, []error{&errortypes.BadInput{
40 -               Message: err.Error(),
41 -           }}
42 -       }
43 -
44 -       var ext openrtb_ext.ImpExtPixfuture
45 -       if err := jsonutil.Unmarshal(bidderExt.Bidder, &ext); err != nil {
46 -           return nil, []error{&errortypes.BadInput{
47 -               Message: err.Error(),
48 -           }}
49 -       }
50
51         reqJSON, err := jsonutil.Marshal(request)
52         if err != nil {
53             errs = append(errs, err)
54             continue
55         }
adapters/pixfuture/pixfuture.go
```

2025-04-16 03:49 UTC, guscarreon commented on adapters/pixfuture/pixfuture.go
> +		headers := http.Header{}
`headers` doesn't seem to change at every turn inside the `for` loop. We could simplify and get a small optimization out of declaring it before entering the `for` loop:
```
30       var errs []error
31       var adapterRequests []*adapters.RequestData
   +
   +     headers := http.Header{}
   +     headers.Set("Content-Type", "application/json")
   +     headers.Set("Accept", "application/json")
32  
33       for i := range request.Imp {
34           imp := &request.Imp[i]
35  
36           // Log raw imp.Ext for debugging
37           var bidderExt adapters.ExtImpBidder
38 *-- 11 lines: if err := jsonutil.Unmarshal(imp.Ext, &bidderExt); err != nil {-------------------------------------------
49           }
50  
51           reqJSON, err := jsonutil.Marshal(request)
52           if err != nil {
53               errs = append(errs, err)
54               continue
55           }
56  
57 -         headers := http.Header{}
58 -         headers.Set("Content-Type", "application/json")
59 -         headers.Set("Accept", "application/json")
60  
61           adapterRequests = append(adapterRequests, &adapters.RequestData{
62               Method:  http.MethodPost,
63               Uri:     a.endpoint,
64               Body:    reqJSON,
65               Headers: headers,
66               ImpIDs:  []string{imp.ID},
67           })
68       }
adapters/pixfuture/pixfuture.go
```

2025-04-17 16:23 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		return openrtb_ext.BidTypeNative, nil
It looks like you're dealing with some discrepancies in your Git repository. 
From your message, it seems like you've made a change to pixfuture.yaml, 
but there’s confusion about coverage.out, and you've frequently rolled back go.mod and go.sum using patch checkout.

2025-04-17 16:25 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		headers := http.Header{}
This section of the code has been updated based on your recommendation.

2025-04-17 20:50 UTC, guscarreon commented on adapters/pixfuture/pixfuture.go
> +		return openrtb_ext.BidTypeNative, nil
> From your message, it seems like you've made a change to pixfuture.yaml,

I didn't. The block of code in my comment above was just meant to illustrate that if you decide to modify file `static/bidder-info/pixfuture.yaml` by adding those `native` entries, Prebid Server Core will not filter out requests that come with native format. I see that in your last update you addressed this comment. Thank you.

2025-04-17 20:52 UTC, guscarreon commented on adapters/pixfuture/pixfuture.go
> +		if err := jsonutil.Unmarshal(imp.Ext, &bidderExt); err != nil {
@pixfuture-media I think a `jsonutil.Unmarshal()` is still found in the newest version of your code. I believe it can be removed too because it seems to exist simply to validate the `imp.Ext` but all of those are vbalidated by Prebid Server Core before they get to this part of the code.

2025-04-17 21:22 UTC, guscarreon reviewed
> there’s confusion about coverage.out

Why, are you having trouble removing it? Maybe you're using and IDE that automatically generates it. If so, you can go to the command line, remove it by hand, and push a commit to this PR. These are the commands for a Linux or Mac machine:
```
$ rm -f coverage.out

$ git commit -m "The coverage.out file got removed"

$ git push https://github.com/pixfuture-media/prebid-server.git master
```

2025-04-21 12:55 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		if err := jsonutil.Unmarshal(imp.Ext, &bidderExt); err != nil {
Please leave this code please.
---
And regarding coverage.out file its not available on my side.
This command sequence that I executed:
1.  
ls -l adapters/pixfuture
total 20
-rw-r--r-- 1 root root 1253 Apr 16 20:24 params_test.go
-rw-r--r-- 1 root root 3651 Apr 17 15:55 pixfuture.go
-rw-r--r-- 1 root root 7063 Apr 17 15:55 pixfuture_test.go
drwxr-xr-x 4 root root 4096 Apr 16 20:24 pixfuturetest
2.
git checkout --patch master go.mod
git checkout --patch master go.sum
3.
git status
git add .
git pull origin master
git commit -m "Made changes regarding GitHub reviews"
git push origin master

2025-04-21 13:16 UTC, guscarreon commented on adapters/pixfuture/pixfuture.go
> +		if err := jsonutil.Unmarshal(imp.Ext, &bidderExt); err != nil {
> And regarding coverage.out file its not available on my side.

Wow. What happens if you do `ls -la coverage.out`?

2025-04-21 13:29 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		if err := jsonutil.Unmarshal(imp.Ext, &bidderExt); err != nil {
#/prebid-server# ls -la adapters/pixfuture
total 36
drwxr-xr-x   3 root root  4096 Apr 17 15:55 .
drwxr-xr-x 244 root root 12288 Apr 16 20:24 ..
-rw-r--r--   1 root root  1253 Apr 16 20:24 params_test.go
-rw-r--r--   1 root root  3651 Apr 17 15:55 pixfuture.go
-rw-r--r--   1 root root  7063 Apr 17 15:55 pixfuture_test.go
drwxr-xr-x   4 root root  4096 Apr 16 20:24 pixfuturetest

2025-04-21 13:46 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		if err := jsonutil.Unmarshal(imp.Ext, &bidderExt); err != nil {
ls -la adapters/pixfuture/coverage.out
ls: cannot access 'adapters/pixfuture/coverage.out': No such file or directory

2025-04-21 20:23 UTC, guscarreon commented on adapters/pixfuture/pixfuture.go
> +		if err := jsonutil.Unmarshal(imp.Ext, &bidderExt); err != nil {
> ls -la adapters/pixfuture/coverage.out

No need for the `adapters/pixfuture/` prefix, just `ls -la coverage.out`

2025-04-22 16:12 UTC, guscarreon reviewed
@pixfuture-media can we also get rid of the changes in `go.mod` and `go.sum`? I tried `git checkout --patch master go.sum` and it worked:
```
~/go/src/github.com/prebid/prebid-server on  PR4117
$ git checkout --patch master go.sum
diff --git b/go.sum a/go.sum
index 0f46493b9..1c03a4d37 100644
--- b/go.sum
+++ a/go.sum
@@ -1018,4 +1018,4 @@ honnef.co/go/tools v0.0.1-2020.1.3/go.mod h1:X/FiERA/W4tHapMX5mGpAtMSVEeEUOyHaw9
 honnef.co/go/tools v0.0.1-2020.1.4/go.mod h1:X/FiERA/W4tHapMX5mGpAtMSVEeEUOyHaw9vFzvIQ3k=
 rsc.io/binaryregexp v0.2.0/go.mod h1:qTv7/COck+e2FymRvadv62gMdZztPaShugOCi3I+8D8=
 rsc.io/quote/v3 v3.1.0/go.mod h1:yEA65RcK8LyAZtP9Kv3t0HmxON59tX3rD+tICJqUlj0=
-rsc.io/sampler v1.3.0/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=
\ No newline at end of file
+rsc.io/sampler v1.3.0/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=
(1/1) Apply this hunk to index and worktree [y,n,q,a,d,e,?]?
```
also `go.mod`:
```
~/go/src/github.com/prebid/prebid-server on  PR4117!
$ git checkout --patch master go.mod
diff --git b/go.mod a/go.mod
index ddbf06bb8..e04389784 100644
--- b/go.mod
+++ a/go.mod
@@ -84,4 +84,4 @@ require (
        google.golang.org/protobuf v1.33.0 // indirect
        gopkg.in/ini.v1 v1.66.4 // indirect
        gopkg.in/yaml.v2 v2.4.0 // indirect
-)
\ No newline at end of file
+)
(1/1) Apply this hunk to index and worktree [y,n,q,a,d,e,?]? y
```
And changes got made:
```
~/go/src/github.com/prebid/prebid-server on  PR4117!
$ git status
On branch PR4117
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   go.mod
        modified:   go.sum
```
After this we can simply update the PR. When you do this commands at Prebid Server root level, what outcome do you get?

2025-04-22 18:05 UTC, pixfuture-media commented
Hi @guscarreon,
se below result of git checkout --patch master go.mod and go.sum
----------------------
root@prebid-adapter-server-side-v1:/production7/prebid-server# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
root@prebid-adapter-server-side-v1:/production7/prebid-server# git add .
root@prebid-adapter-server-side-v1:/production7/prebid-server# git pull origin master
From https://github.com/pixfuture-media/prebid-server
 * branch              master     -> FETCH_HEAD
Already up to date.
root@prebid-adapter-server-side-v1:/production7/prebid-server# git commit -m "Made changes regarding GitHub reviews"
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
root@prebid-adapter-server-side-v1:/production7/prebid-server# git checkout --patch master go.mod
No changes.
root@prebid-adapter-server-side-v1:/production7/prebid-server# git checkout --patch master go.sum
No changes.
root@prebid-adapter-server-side-v1:/production7/prebid-server# git push origin master
Username for 'https://github.com': client-support@pixfuture.com
Password for 'https://client-support%40pixfuture.com@github.com':
Everything up-to-date
root@prebid-adapter-server-side-v1:/production7/prebid-server# git checkout --patch master go.sum

2025-04-22 20:36 UTC, guscarreon commented
Ohh I see. Then lets modify the commands a little bit. Lets do 
```
$ git checkout --patch origin/master go.mod
$ git checkout --patch origin/master go.sum
```
instead of 
```
$ git checkout --patch master go.mod
$ git checkout --patch master go.sum
```
That extra `origin/` tells `git` to pull `go.mod` and `go.sum` from this repo's `master` branch as opposed to your local `master` branch. Below is the output I get locally. Notice how in the `Apply this hunk to index and worktree [y,n,q,a,d,e,?]?` prompt I have to agree by entering `y`:
```
~/go/src/github.com/prebid/prebid-server on  PR4117
$ git checkout --patch origin/master go.mod
diff --git b/go.mod a/go.mod
index ddbf06bb8..e04389784 100644
--- b/go.mod
+++ a/go.mod
@@ -84,4 +84,4 @@ require (
        google.golang.org/protobuf v1.33.0 // indirect
        gopkg.in/ini.v1 v1.66.4 // indirect
        gopkg.in/yaml.v2 v2.4.0 // indirect
-)
\ No newline at end of file
+)
(1/1) Apply this hunk to index and worktree [y,n,q,a,d,e,?]? y

~/go/src/github.com/prebid/prebid-server on  PR4117!
$ git checkout --patch origin/master go.sum
diff --git b/go.sum a/go.sum
index 0f46493b9..1c03a4d37 100644
--- b/go.sum
+++ a/go.sum
@@ -1018,4 +1018,4 @@ honnef.co/go/tools v0.0.1-2020.1.3/go.mod h1:X/FiERA/W4tHapMX5mGpAtMSVEeEUOyHaw9
 honnef.co/go/tools v0.0.1-2020.1.4/go.mod h1:X/FiERA/W4tHapMX5mGpAtMSVEeEUOyHaw9vFzvIQ3k=
 rsc.io/binaryregexp v0.2.0/go.mod h1:qTv7/COck+e2FymRvadv62gMdZztPaShugOCi3I+8D8=
 rsc.io/quote/v3 v3.1.0/go.mod h1:yEA65RcK8LyAZtP9Kv3t0HmxON59tX3rD+tICJqUlj0=
-rsc.io/sampler v1.3.0/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=
\ No newline at end of file
+rsc.io/sampler v1.3.0/go.mod h1:T1hPZKmBbMNahiBKFy5HrXp6adAjACjK9JXDnKaTXpA=
(1/1) Apply this hunk to index and worktree [y,n,q,a,d,e,?]? y


~/go/src/github.com/prebid/prebid-server on  PR4117!
$ git status
On branch PR4117
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   go.mod
        modified:   go.sum
```
Then you should simply do: `git commit -m "Modified go.sum and go.mod format"` followed by `git push origin master`. Let me know how it goes.

2025-04-22 20:50 UTC, pixfuture-media commented
Sory Brian,
but no different (
root@prebid-adapter-server-side-v1:/production7/prebid-server# git checkout --patch origin/master go.mod
No changes.
root@prebid-adapter-server-side-v1:/production7/prebid-server# git checkout --patch origin/master go.sum
No changes.
root@prebid-adapter-server-side-v1:/production7/prebid-server#

2025-04-23 16:34 UTC, bsardo commented
@pixfuture-media it looks like the only changes in `go.mod` and `go.sum` now are that you removed a newline at the end of each of these files. Just add the newline back to each file and push up a new commit with these changes.

2025-04-24 20:31 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/supplemental/pix_id_too_short.json
The https://sync.pixfuture.com/cookiesync is unavailable outside business hours until the Prebid adapter is operational. 
I can run it overnight if you want to test it.

2025-04-24 20:31 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/supplemental/pix_id_too_short.json
I deleted the bidder-params/pixfuture.json.

2025-04-24 20:32 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/exemplary/banner.json
Fixed.

2025-04-24 20:32 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture_test.go
> +}
Fixed

2025-04-24 20:33 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/supplemental/no_banner.json
Deleted

2025-04-24 20:33 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/supplemental/missing_params.json
Deleted

2025-04-24 20:34 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +	}
Statement deleted

2025-04-24 20:35 UTC, pixfuture-media commented
I started the https://sync.pixfuture.com/cookiesync

2025-04-25 18:26 UTC, bsardo commented on adapters/pixfuture/pixfuturetest/supplemental/pix_id_too_short.json
> The https://sync.pixfuture.com/cookiesync is unavailable outside business hours until the Prebid adapter is operational. I can run it overnight if you want to test it.

Thanks, I just tested it. I don't see a request being made to the PBS host setuid endpoint, which in my test case is localhost://setuid. This is mandatory as it is how we populate the PBS cookie with your UID. Since you've declared your usersync to be of type redirect, you should be redirecting to this endpoint.
I also see that you're injecting a lot (18) of iframe and img tags onto the page in what appears to be your own syncs with various bidders. We generally recommend that you limit this to no more than 10 if you're so inclined to do this at all.

2025-04-25 18:27 UTC, bsardo commented on adapters/pixfuture/pixfuturetest/supplemental/pix_id_too_short.json
> I deleted the bidder-params/pixfuture.json.

Why do you now want to delete this? Don't you need `pix_id`? This is the file where you should declare this and specify any rules around that parameter.

2025-04-28 15:02 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/supplemental/pix_id_too_short.json
> > I deleted the bidder-params/pixfuture.json.
> 
> Why do you now want to delete this? Don't you need `pix_id`? This is the file where you should declare this and specify any rules around that parameter.

***I deleted the bidder-params/pixfuture.json.***
Sorry, I provided the wrong path, it's not "bidder-params/pixfuture.json"

2025-04-28 19:56 UTC, pixfuture-media commented on adapters/pixfuture/pixfuturetest/supplemental/pix_id_too_short.json
The Cookie Sync functionality has been fixed. The server is running now til you finish the test.

2025-06-23 18:21 UTC, pixfuture-media commented
All requested changes have been made. 
Please provide what's next.

2025-07-08 13:44 UTC, pixfuture-media commented
Hello Prebid Server Team,
We would appreciate it if you could review our recent submission and advise us on the next steps to take. Please let us know if any adjustments or actions are needed on our side.
Looking forward to your feedback.
Best regards,
Vitali I.

2025-07-08 15:59 UTC, scr-oath commented on adapters/pixfuture/params_test.go
> +	}
**nitpick**: Prefer testify assertions (require for instant fail)
```suggestion
	require.NoError(t, err, "Failed to fetch the json schema.")
```

2025-07-08 16:00 UTC, scr-oath commented on adapters/pixfuture/params_test.go
> +		}
**nitpick**: prefer testify assertions (assert for eventually fail)

```suggestion
		assert.NoErrorf(t, validator.Validate(openrtb_ext.BidderPixfuture, json.RawMessage(p)), "Schema rejected valid params: %s", p)
```

2025-07-08 16:01 UTC, scr-oath commented on adapters/pixfuture/params_test.go
> +	if err != nil {
**nitpick**: testify require

2025-07-08 16:02 UTC, scr-oath commented on adapters/pixfuture/params_test.go
> +		if err := validator.Validate(openrtb_ext.BidderPixfuture, json.RawMessage(p)); err == nil {
**nitpick**: testify assert

2025-07-08 16:04 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +		imp := &request.Imp[i]
**suggestion** (not-blocking): you can use the iterutil.SlicePointerValues here

https://github.com/prebid/prebid-server/blob/master/util/iterutil/slices.go#L17C6-L17C24

```suggestion
	for imp := range iterutil.SlicePointerValues(request.Imp)
```

2025-07-08 16:07 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +		}
Or… slice-notation to grab just the one imp.

```go
requestCopy := *request
requestCopy.Imp = request.Imp[i:i+1]
reqJSON, err := jsonutil.Marshal(requestCopy)
```

2025-07-21 20:00 UTC, pixfuture-media commented on adapters/pixfuture/params_test.go
> +	}
Code has been updated based on your recommendation. Changes are now live on GitHub.

2025-07-21 20:00 UTC, pixfuture-media commented on adapters/pixfuture/params_test.go
> +		}
Code has been updated based on your recommendation. Changes are now live on GitHub.

2025-07-21 20:03 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		imp := &request.Imp[i]
I wasn’t able to refactor the code as per your recommendation due to an issue importing the iterutil module.

2025-07-21 20:05 UTC, pixfuture-media commented on adapters/pixfuture/params_test.go
> +	if err != nil {
Code has been updated based on your recommendation. Changes are now live on GitHub.

2025-07-21 20:06 UTC, pixfuture-media commented on adapters/pixfuture/params_test.go
> +		if err := validator.Validate(openrtb_ext.BidderPixfuture, json.RawMessage(p)); err == nil {
Code has been updated based on your recommendation. Changes are now live on GitHub.

2025-07-21 20:39 UTC, scr-oath requested changes

2025-07-21 20:39 UTC, scr-oath commented on adapters/pixfuture/params_test.go
> +}
The pattern that is used quite often is to create a list of tests and to t.Run each - that way each test is counted individually in any reports, and can be run in IDE directly / individually since the test can be referenced with a pattern. Given what you have below, something like this would be good:

```suggestion
func TestValidParams(t *testing.T) {
	validator, err := openrtb_ext.NewBidderParamsValidator("../../static/bidder-params")
	require.NoError(t, err, "Failed to fetch the json schema.")

	tests := struct{
		name string
		json string
	}{
		{
			name: "Minimum length satisfied",
			json: `{"pix_id": "123"}`,
		},
		{
			name: "Longer valid string",
			json: `{"pix_id": "abcdef"}`,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func() {
		assert.NoErrorf(t, validator.Validate(openrtb_ext.BidderPixfuture, json.RawMessage(tt.json)), "Schema rejected valid params: %s", p)
		})
	}
}
```

2025-07-21 20:39 UTC, scr-oath commented on adapters/pixfuture/params_test.go
> +func TestInvalidParams(t *testing.T) {
This can also be refactored to use the tests pattern and t.Run.

2025-07-21 21:02 UTC, pixfuture-media commented on adapters/pixfuture/params_test.go
> +func TestInvalidParams(t *testing.T) {
The recommended code refactoring has been completed.

2025-07-21 21:03 UTC, pixfuture-media commented on adapters/pixfuture/params_test.go
> +}
The recommended code refactoring has been completed.

2025-07-21 22:40 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +		imp := &request.Imp[i]
#4447 should have resolved that, but the code you have now is good.

2025-07-25 15:27 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		imp := &request.Imp[i]
This code was fixed by [scr-oath recommendations

2025-07-25 19:39 UTC, scr-oath approved these changes

2025-07-25 19:39 UTC, scr-oath commented on adapters/pixfuture/params_test.go
> +		tt := tt // capture range variable
**nitpick** (not-blocking): This hasn't been needed for several versions of go now

### Why `tt := tt` is no longer necessary in Go

The line:

```go
tt := tt // capture range variable
```

was historically required in Go when using range variables inside subtests or goroutines, to "capture" the loop variable at each iteration. This prevented bugs due to all closures sharing the same variable in older Go versions.

**Change in Go 1.22:**

As of Go 1.22, this is no longer necessary. The Go release notes state:

> "The iteration variables of for loops are now per-iteration copies, eliminating a common source of bugs when using closures or goroutines inside loops."  
> — [Go 1.22 Release Notes – Iteration Variables](https://go.dev/doc/go1.22#loopvar)

**Summary:**  
If your project requires Go 1.22 or later, you can safely remove `tt := tt` from range-based subtests and goroutines.  
See the [official Go 1.22 release notes](https://go.dev/doc/go1.22#loopvar) for more details.

2025-07-25 19:49 UTC, pixfuture-media commented on adapters/pixfuture/params_test.go
> +		tt := tt // capture range variable
Got it—so it’s not absolutely required to change the code, right?

2025-07-25 19:53 UTC, scr-oath commented on adapters/pixfuture/params_test.go
> +		tt := tt // capture range variable
Nope - I approved with this as an observation (as in "see something; say something" 😄 )

https://conventionalcomments.org/

Describes the (non-blocking) decoration

2025-07-25 19:57 UTC, pixfuture-media commented on adapters/pixfuture/params_test.go
> +		tt := tt // capture range variable
Thank you, dear Sheridan!

2025-07-30 14:15 UTC, pixfuture-media commented on adapters/pixfuture/params_test.go
> +		tt := tt // capture range variable
Hi Sheridan,
After applying all the recent changes, the function call to "func (a *adapter) MakeRequests(request *openrtb2.BidRequest..." in "pixfuture.go" stopped being called.  
Could you help identify what might be causing this issue?

2025-08-18 13:29 UTC, pixfuture-media commented
Hi team,
We fixed all issues. What's next?
Let us know, please.
Vitali Ioussoupov
Senior Developer,
Pixfutuere Media Inc

2025-08-26 21:04 UTC, guscarreon commented
> Hi team, We fixed all issues. What's next? Let us know, please. Vitali Ioussoupov Senior Developer, Pixfutuere Media Inc

Hi @pixfuture-media . Can you please correct the validation error? These happen because a test case is not passing. You can run the `./validate.sh` script included in this repo, to run all test cases and spot the one that's not passing.

2025-10-27 16:35 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +	if response.StatusCode == http.StatusNoContent {
Use prebid-server helper functions for consistency:

```go
if adapters.IsResponseStatusCodeNoContent(response) {
    return nil, nil
}

if err := adapters.CheckResponseStatusCodeForErrors(response); err != nil {
    return nil, []error{err}
}
```

This provides better error messages and handles BadRequest as BadInput error type.

2025-10-27 16:35 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +		var bidderExt struct {
Use the defined type instead of anonymous struct and add validation:

```go
var bidderExt adapters.ExtImpBidder
var pixfutureExt openrtb_ext.ImpExtPixfuture

if err := jsonutil.Unmarshal(imp.Ext, &bidderExt); err \!= nil {
    errs = append(errs, err)
    continue
}
if err := jsonutil.Unmarshal(bidderExt.Bidder, &pixfutureExt); err \!= nil {
    errs = append(errs, err)
    continue
}
if pixfutureExt.PixID == "" {
    errs = append(errs, &errortypes.BadInput{Message: "Missing required parameter pix_id"})
    continue
}
```

This ensures consistency with the defined schema type and adds runtime validation.

2025-10-27 16:36 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +func getMediaTypeForBid(bid openrtb2.Bid) (openrtb_ext.BidType, error) {
Support OpenRTB 2.6 standard `bid.MType` field before falling back to custom extension:

```go
func getMediaTypeForBid(bid openrtb2.Bid) (openrtb_ext.BidType, error) {
    // First try standard MType field (OpenRTB 2.6)
    switch bid.MType {
    case openrtb2.MarkupBanner:
        return openrtb_ext.BidTypeBanner, nil
    case openrtb2.MarkupVideo:
        return openrtb_ext.BidTypeVideo, nil
    case openrtb2.MarkupNative:
        return openrtb_ext.BidTypeNative, nil
    }
    
    // Fallback to custom extension
    var ext struct {
        Prebid struct {
            Type string `json:"type"`
        } `json:"prebid"`
    }
    if err := jsonutil.Unmarshal(bid.Ext, &ext); err != nil {
        return "", &errortypes.BadServerResponse{
            Message: fmt.Sprintf("Failed to parse bid ext for impression %s: %v", bid.ImpID, err),
        }
    }
    
    switch ext.Prebid.Type {
    case "banner":
        return openrtb_ext.BidTypeBanner, nil
    case "video":
        return openrtb_ext.BidTypeVideo, nil
    case "native":
        return openrtb_ext.BidTypeNative, nil
    default:
        return "", &errortypes.BadServerResponse{
            Message: fmt.Sprintf("Unknown bid type for impression %s", bid.ImpID),
        }
    }
}
```

This follows the OpenRTB 2.6 standard and provides better error messages.

2025-10-27 16:36 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +	bidResponse := adapters.NewBidderResponse()
Pre-allocate response capacity to avoid slice reallocations:

```go
expectedBids := 0
for i := range bidResp.SeatBid {
    expectedBids += len(bidResp.SeatBid[i].Bid)
}
bidResponse := adapters.NewBidderResponseWithBidsCapacity(expectedBids)
```

This improves performance by avoiding multiple memory allocations as bids are appended.

2025-10-27 16:36 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +package pixfuture
Add package documentation:

```go
// Package pixfuture implements the Pixfuture adapter for Prebid Server.
package pixfuture
```

2025-10-27 16:53 UTC, scr-oath commented on adapters/pixfuture/pixfuture.go
> +	bidResponse := adapters.NewBidderResponse()
You could also use the iterutils for the outer loop on SeatBid - this was Claude's comment, which may not have known about that preference. I'm also not terribly sure I agree with this nitpick saving that much, but do consider it and respond/defend.

2025-10-28 13:36 UTC, pixfuture-media commented
Thank you, Sheridan,
We will fix it

2025-11-17 19:15 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +	if response.StatusCode == http.StatusNoContent {
The recommended changes have been implemented.

2025-11-17 19:15 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +		var bidderExt struct {
The recommended changes have been implemented.

2025-11-17 19:15 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +func getMediaTypeForBid(bid openrtb2.Bid) (openrtb_ext.BidType, error) {
The recommended changes have been implemented.

2025-11-17 19:16 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +package pixfuture
The recommended changes have been implemented.

2025-11-17 19:16 UTC, pixfuture-media commented on adapters/pixfuture/pixfuture.go
> +	bidResponse := adapters.NewBidderResponse()
The recommended changes have been implemented.

2025-11-17 19:21 UTC, pixfuture-media commented
Dear Sheridan, we made the requested changes. Please review and approve the merge.

2025-12-19 17:45 UTC, pixfuture-media commented
Hi team, please review our code and merge it.

2026-02-10 21:52 UTC, scr-oath requested changes
## Review Update - Pixfuture Adapter

Thanks for the continued work on this adapter. I've done a thorough re-review of the current state. Many of the earlier comments have been addressed (struct naming, alphabetical ordering in `exchange/adapter_builders.go`, use of `http.MethodPost`, deleted commented-out code, etc.). However, several issues remain unresolved:

---

### 🔴 BLOCKING

**1. Alphabetical ordering in `openrtb_ext/bidders.go` (still broken)**

`BidderPixfuture` is at the end of the `coreBidderNames` array (after `BidderZmaticoo`). It needs to be moved to its correct alphabetical position between `BidderPGAMSsp` and `BidderPlaydigo`. The `const` block is correct but the array is not.

**2. Missing `userMacro` in cookie sync configuration (`pixfuture.yaml`)**

The `userSync.redirect` section is missing a `userMacro` field. Without this, `{{.UserMacro}}` in the default `RedirectURL` template resolves to an empty string, meaning the `/setuid` callback receives `uid=` (empty) and no user ID is ever stored. The entire cookie sync becomes non-functional.

Please add the macro your sync endpoint uses to substitute the user ID, e.g.:
```yaml
userSync:
  redirect:
    url: "https://sync.pixfuture.com/cookiesync?gdpr={{.GDPR}}&consent={{.GDPRConsent}}&us_privacy={{.USPrivacy}}&redirect={{.RedirectURL}}"
    userMacro: "${UID}"
```

**3. Cookie sync endpoint must redirect to PBS `/setuid`**

As @bsardo and @bretg noted, the sync endpoint must ultimately redirect to the PBS host's `/setuid` endpoint. The `{{.RedirectURL}}` macro handles constructing that URL, but your server at `sync.pixfuture.com/cookiesync` must honor the `redirect` query parameter and redirect the user there with their UID appended. Please confirm this is working.

**4. Missing GPP privacy parameters in sync URL**

Add GPP macros for compliance with multi-state privacy frameworks:
```
&gpp={{.GPP}}&gpp_sid={{.GPPSID}}
```

---

### 🟡 SUGGESTIONS (non-blocking but strongly recommended)

**5. Memory efficiency in loop patterns (`pixfuture.go`)**

In `MakeBids`, the `for _, bid := range` loop copies each `openrtb2.Bid` struct (which is large). Use index-based iteration instead:

```go
for i := range bidResp.SeatBid {
    for j := range bidResp.SeatBid[i].Bid {
        bid := &bidResp.SeatBid[i].Bid[j]
        bidType, err := getMediaTypeForBid(bid)
        // ...
        bidResponse.Bids = append(bidResponse.Bids, &adapters.TypedBid{
            Bid:     bid,
            BidType: bidType,
        })
    }
}
```

Also update `getMediaTypeForBid` to accept a pointer: `func getMediaTypeForBid(bid *openrtb2.Bid)`.

**6. Duplicate test files**

`supplemental/no_bids.json` and `supplemental/status_204.json` are byte-identical (both test HTTP 204). Change `no_bids.json` to return HTTP 200 with an empty `seatbid` array to test the empty-bids code path at line 121.

**7. Test coverage gaps**

Consider adding tests for:
- Malformed JSON response body (exercises error path at lines 88-92)
- Multi-impression request (all current tests are single-impression)
- Bid response with `mtype` field set (currently all tests use the `ext.prebid.type` fallback — none exercise the OpenRTB 2.6 MType code path)

---

### ✅ Previously raised comments that are now resolved

- Struct renamed from `PixfutureAdapter` to `adapter` ✅
- `testdata` directory replaced with `pixfuturetest/exemplary` + `supplemental` ✅
- `config.go` changes reverted ✅
- `go.mod`/`go.sum` no longer modified ✅
- `coverage.out` no longer in the diff ✅
- `docs/pixfuture.md` removed from PR ✅
- `exchange/adapter_builders.go` alphabetical ordering fixed ✅
- `TestJsonSamples` now calls `RunJSONBidderTest` ✅
- `minLength: 3` added to `pix_id` schema ✅
- Uses `http.MethodPost` instead of `"POST"` ✅
- Commented-out code deleted ✅
- Uses `adapters.IsResponseStatusCodeNoContent` / `CheckResponseStatusCodeForErrors` ✅
- GVL Vendor ID 839 verified ✅
- Maintainer email verified ✅

2026-02-13 19:39 UTC, pixfuture-media commented
Hi Sheridan,

We have resolved the following issues:
Alphabetical Ordering: Fixed the ordering in openrtb_ext/bidders.go.
Cookie Sync Configuration: Fixed the missing userMacro in pixfuture.yaml.
Cookie Sync Endpoint: Updated the endpoint to ensure it correctly redirects to the PBS /setuid endpoint.
Please let us know once this code has been merged into production.

Best regards,
Vitali I.

2026-02-26 14:42 UTC, pixfuture-media commented
Hello Sheridan,

I hope you’re doing well.

We’ve resolved the following items:

* **Alphabetical ordering** – Fixed the ordering in `openrtb_ext/bidders.go`.
* **Cookie sync configuration** – Added the missing `userMacro` in `pixfuture.yaml`.
* **Cookie sync endpoint** – Updated the endpoint so it correctly redirects to the PBS `/setuid` endpoint.

Could you please let us know once these changes have been merged into production?

Thanks again for your support!

Best regards,
Vitali I.

2026-03-09 20:44 UTC, pixfuture-media commented
Hello Sheridan,

I hope you’re doing well.
We’ve completed the following updates:
• 	Alphabetical ordering – Corrected the ordering in .
• 	Cookie sync configuration – Added the missing  in .
• 	Cookie sync endpoint – Updated the endpoint so it now redirects properly to the PBS  endpoint.
Could you please let us know once these changes have been merged into production?
Thanks again for your support.

Best regards,
Vitali I.

2026-03-10 18:47 UTC, closed without merging